image: node:16

stages:
  - install_dependencies
  - build

install_dependencies:
  stage: install_dependencies
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
